window_padding_width    10.0 15.0
confirm_os_window_close 0

background_opacity      0.8
background_blur         1

font_family             Iosevka
font_weight             400

font_size               14.0
disable_ligratures      never
